baseURL = "https://abdulai-gassama.netlify.app/"
title = "HugoTeX"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[author]
  name = "Abdulai"
  abstract = "Hello, this my own personal website.
             The font is purposedly hard to read in case to quickly disinterest"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
