baseURL = "https://abdulai-gassama.netlify.app/"
title = "間欠泉"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[author]
  name = "Abdulai Gassama"
  abstract = "Hello, this my own personal website"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
